services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/app:cached
    command: sleep infinity
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: mfc_reception_development
      DATABASE_USER: postgres
      DATABASE_PASS: password
      REDIS_HOST: redis://redis:6379/1
    networks:
      - mfc_reception

  db:
    image: harbor.rnds.pro/dockerhub/library/postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mfc_reception_development
      POSTGRES_PASSWORD: password
    networks:
      - mfc_reception

  redis:
    image: harbor.rnds.pro/dockerhub/library/redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - mfc_reception

networks:
  mfc_reception:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
